"""Golden snapshot tests — pin exact numerical output for all strategies.

Each test loads a golden fixture (JSON) generated by tests/golden/generate_golden.py
and compares the current engine output against the stored expectation.

Any engine change that shifts a number will cause a visible test failure.
To update fixtures after an *intentional* change:
    python tests/golden/generate_golden.py

Then re-run:
    python -m pytest test_golden.py -v
"""
import json
import os
import copy
import unittest

from retirement_engine import RetirementEngine
from drawdown_strategies import normalize_config
from config_helpers import make_extended_config, validate_config

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "tests", "golden")

FIXTURES = [
    "fixed_target",
    "fixed_percentage",
    "vanguard_dynamic",
    "guyton_klinger",
    "arva",
    "arva_guardrails",
    "fixed_target_shortfall",
]


def _load_fixture(name):
    path = os.path.join(GOLDEN_DIR, f"{name}.json")
    with open(path) as f:
        return json.load(f)


def _extract_year(yr):
    return {
        "age": yr["age"],
        "target_net": round(yr["target_net"], 2),
        "net_income_achieved": round(yr["net_income_achieved"], 2),
        "total_capital": round(yr["total_capital"], 2),
        "shortfall": yr["shortfall"],
    }


def _extract_summary(s):
    return {
        "sustainable": s["sustainable"],
        "first_shortfall_age": s["first_shortfall_age"],
        "remaining_capital": round(s["remaining_capital"], 2),
        "end_age": s["end_age"],
    }


class GoldenTestBase(unittest.TestCase):
    """Base class for golden snapshot tests."""

    fixture_name = None

    @classmethod
    def setUpClass(cls):
        if cls.fixture_name is None:
            raise unittest.SkipTest("Base class — no fixture")
        cls.fixture = _load_fixture(cls.fixture_name)
        cfg = copy.deepcopy(cls.fixture["config"])
        normalize_config(cfg)
        cls.result = RetirementEngine(cfg).run_projection()
        ext_cfg = make_extended_config(cfg)
        cls.ext_result = RetirementEngine(ext_cfg).run_projection()
        cls.plan_end_age = cfg["personal"]["end_age"]

    def test_config_validates(self):
        """Config passes validation with no errors."""
        cfg = copy.deepcopy(self.fixture["config"])
        normalize_config(cfg)
        errors = validate_config(cfg)
        self.assertEqual(errors, [], f"Config validation errors: {errors}")

    def test_summary_matches(self):
        """Summary fields match golden fixture exactly."""
        actual = _extract_summary(self.result["summary"])
        expected = self.fixture["summary"]
        self.assertEqual(actual["sustainable"], expected["sustainable"],
                         f"sustainable mismatch: {actual} vs {expected}")
        self.assertEqual(actual["first_shortfall_age"], expected["first_shortfall_age"])
        self.assertAlmostEqual(actual["remaining_capital"],
                               expected["remaining_capital"], delta=0.01)
        self.assertEqual(actual["end_age"], expected["end_age"])

    def test_year_count_matches(self):
        """Same number of projection years."""
        actual_years = [_extract_year(y) for y in self.result["years"]]
        self.assertEqual(len(actual_years), len(self.fixture["years"]))

    def test_year_by_year_matches(self):
        """Every year's key fields match the golden fixture."""
        for i, yr in enumerate(self.result["years"]):
            actual = _extract_year(yr)
            expected = self.fixture["years"][i]
            age = expected["age"]
            self.assertEqual(actual["age"], age)
            self.assertAlmostEqual(
                actual["target_net"], expected["target_net"], delta=0.01,
                msg=f"Age {age}: target_net")
            self.assertAlmostEqual(
                actual["net_income_achieved"], expected["net_income_achieved"],
                delta=0.01, msg=f"Age {age}: net_income_achieved")
            self.assertAlmostEqual(
                actual["total_capital"], expected["total_capital"], delta=0.01,
                msg=f"Age {age}: total_capital")
            self.assertEqual(
                actual["shortfall"], expected["shortfall"],
                msg=f"Age {age}: shortfall flag")

    def test_extended_projection_parity(self):
        """Years within plan end are identical between normal and extended."""
        normal_years = [_extract_year(y) for y in self.result["years"]]
        ext_years_within_plan = [
            _extract_year(y) for y in self.ext_result["years"]
            if y["age"] <= self.plan_end_age
        ]
        self.assertEqual(len(normal_years), len(ext_years_within_plan),
                         "Year count mismatch between normal and extended")
        for i, (ny, ey) in enumerate(zip(normal_years, ext_years_within_plan)):
            self.assertEqual(ny["age"], ey["age"])
            self.assertAlmostEqual(
                ny["target_net"], ey["target_net"], delta=0.01,
                msg=f"Parity age {ny['age']}: target_net")
            self.assertAlmostEqual(
                ny["net_income_achieved"], ey["net_income_achieved"],
                delta=0.01, msg=f"Parity age {ny['age']}: net_income_achieved")
            self.assertAlmostEqual(
                ny["total_capital"], ey["total_capital"], delta=0.01,
                msg=f"Parity age {ny['age']}: total_capital")
            self.assertEqual(
                ny["shortfall"], ey["shortfall"],
                msg=f"Parity age {ny['age']}: shortfall flag")


# ---------- Concrete test classes, one per fixture ----------

class TestGolden_FixedTarget(GoldenTestBase):
    fixture_name = "fixed_target"


class TestGolden_FixedPercentage(GoldenTestBase):
    fixture_name = "fixed_percentage"


class TestGolden_VanguardDynamic(GoldenTestBase):
    fixture_name = "vanguard_dynamic"


class TestGolden_GuytonKlinger(GoldenTestBase):
    fixture_name = "guyton_klinger"


class TestGolden_ARVA(GoldenTestBase):
    fixture_name = "arva"


class TestGolden_ARVAGuardrails(GoldenTestBase):
    fixture_name = "arva_guardrails"


class TestGolden_FixedTargetShortfall(GoldenTestBase):
    fixture_name = "fixed_target_shortfall"

    def test_is_shortfall(self):
        """This fixture must report a shortfall."""
        self.assertFalse(self.result["summary"]["sustainable"])
        self.assertIsNotNone(self.result["summary"]["first_shortfall_age"])


if __name__ == "__main__":
    unittest.main()
